import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useAppDispatch, useAppSelector } from '../../store/hooks';
import { useEffect } from 'react';
import { setAccounts, setProvider, setSelectedAccount } from '../../store/slices/accountSlice';
import { getAccounts } from '../../services/accountService';
import { ethers } from 'ethers';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>HomeChain</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className=''>
        </div>
      </main>
    </>
  )
}
