import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useAppDispatch, useAppSelector } from '../../store/hooks';
import { ContractsEnum } from '@/enums/ContractsEnum';
import { NoContractSelected } from '@/components/NoContractSelected';
import { PagesEnum } from '@/enums/PagesEnum';
import { OverviewPage } from '@/components/pages/OverviewPage';
import { GraphsPage } from '@/components/pages/GraphsPage';
import { ClientPage } from '@/components/pages/ClientPage';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const navigationPage = useAppSelector((state) => state.navigation.page);

  return (
    <>
      <Head>
        <title>HomeChain</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className=''>
          {navigationPage === PagesEnum.Overview && <OverviewPage />}
          {navigationPage === PagesEnum.Graphs && <GraphsPage />}
          {navigationPage === PagesEnum.Client && <ClientPage />}
        </div>
      </main>
    </>
  )
}
